name: Tshella_Security
description: A security app frontend in Flutter

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.5
  encrypt: ^5.0.0
  connectivity_plus: ^6.1.0
  material_design_icons_flutter: ^5.0.6595
  font_awesome_flutter: ^10.4.0
  file_picker: ^5.2.2
  syncfusion_flutter_charts: ^20.4.48
  syncfusion_flutter_gauges: ^20.4.48
  workmanager: ^0.5.2
  flutter_local_notifications: ^16.0.0
  android_alarm_manager_plus: ^4.0.4

 



dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  string_scanner: ^1.4.0
  async: ^2.12.0
  characters : ^1.3.1
  clock: ^1.1.2
  collection: ^1.19.1 
  http_parser: ^4.1.1
  js: ^0.7.1
  material_color_utilities : ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1

fonts:
  - family: Orbitron
    fonts:
      - asset: assets/fonts/Orbitron-Regular.ttf
      - asset: assets/fonts/Orbitron-Bold.ttf